### ISSUE TITLE
What is it good for. Absolutely nothing. How to use Node.js for 1 million concurrent connections

### ISSUE THREAD

**Issue by quinnliu** [Laybium/laybium_server#4]
1. http://blog.caustik.com/2012/08/19/node-js-w1m-concurrent-connections/
2. https://www.toptal.com/nodejs/why-the-hell-would-i-use-node-js

@vatteh after reading these I have learned we want to do as little computation on the node.js server as possible.

```
When it comes to heavy computation, Node.js is not the best 
platform around. No, you definitely don’t want to build a 
Fibonacci computation server in Node.js. In general, any CPU 
intensive operation annuls all the throughput benefits Node 
offers with its event-driven, non-blocking I/O model because 
any incoming requests will be blocked while the thread is 
occupied with your number-crunching.
```

**Comment by vatteh** [comment]
Ok. This can end up changing how we implement our app from now on. I agree, we can make it so that more computation is done on the client, but we should be aware of the cases when it starts to come at the price of code being hard to read and understand. It's just unlikely we will be dealing with this many users any time soon.

**Comment by quinnliu** [comment]
agreed
